SELECT *
  FROM CUSTOMER, ORDERS
 WHERE CUSTOMER.CUSTID = ORDERS.CUSTID;


SELECT CUSTOMER.NAME, ORDERS.ORDERDATE,BOOK.BOOKNAME,BOOK.PRICE, ORDERS.SALEPRICE
  FROM CUSTOMER, ORDERS, BOOK
 WHERE CUSTOMER.CUSTID = ORDERS.CUSTID
   AND BOOK.BOOKID = ORDERS.BOOKID;

SELECT T1.NAME, T2.ORDERDATE,T3.BOOKNAME,T3.PRICE, T2.SALEPRICE
  FROM CUSTOMER T1, ORDERS T2, BOOK T3
 WHERE T1.CUSTID = T2.CUSTID
   AND T3.BOOKID = T2.BOOKID;

SELECT T1.NAME, 				--고객명
			 T2.ORDERDATE,		--주문일
			 T3.BOOKNAME,			--도서명
			 T3.PRICE, 				--원가
			 T2.SALEPRICE			--판매가
  FROM CUSTOMER T1, ORDERS T2, BOOK T3
 WHERE T1.CUSTID = T2.CUSTID
   AND T3.BOOKID = T2.BOOKID
   AND T2.SALEPRICE > 8000;


	SELECT T1.NAME,SUM(T2.SALEPRICE)
	  FROM CUSTOMER T1, ORDERS T2, BOOK T3
	 WHERE T1.CUSTID = T2.CUSTID
	   AND T3.BOOKID = T2.BOOKID
	   AND T2.SALEPRICE > 8000
GROUP BY T1.CUSTID,T1.NAME 
  HAVING SUM(T2.SALEPRICE) > 30000
ORDER BY T1.CUSTID DESC	;